# Generated by Django 6.0.3 on 2026-07-09 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cover_image', models.ImageField(blank=True, upload_to='highlights/covers/%Y/%m/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryHighlightItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('highlight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='profiles.storyhighlight')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlight_items', to='profiles.story')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('highlight', 'story')},
            },
        ),
    ]
