# Generated by Django 6.0.3 on 2026-03-23 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bible', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bibletag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bible_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bibleverse',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='bible.biblechapter'),
        ),
        migrations.AddField(
            model_name='favoriteverse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_verses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favoriteverse',
            name='verse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='bible.bibleverse'),
        ),
        migrations.AddField(
            model_name='highlightcategory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlight_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='highlighttag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='bible.bibletag'),
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.biblebook'),
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.biblechapter'),
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studynote',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bible.highlightcategory'),
        ),
        migrations.AddField(
            model_name='studynote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bible_study_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='verseannotation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verse_annotations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='versehighlight',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highlights', to='bible.highlightcategory'),
        ),
        migrations.AddField(
            model_name='versehighlight',
            name='end_verse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights_end', to='bible.bibleverse'),
        ),
        migrations.AddField(
            model_name='versehighlight',
            name='start_verse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights_start', to='bible.bibleverse'),
        ),
        migrations.AddField(
            model_name='versehighlight',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verse_highlights', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='verseannotation',
            name='highlight',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='annotation', to='bible.versehighlight'),
        ),
        migrations.AddField(
            model_name='highlighttag',
            name='highlight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='bible.versehighlight'),
        ),
        migrations.AlterUniqueTogether(
            name='biblechapter',
            unique_together={('book', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='bibletag',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='bibleverse',
            unique_together={('chapter', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='favoriteverse',
            unique_together={('user', 'verse')},
        ),
        migrations.AlterUniqueTogether(
            name='highlightcategory',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='readingprogress',
            unique_together={('user', 'book', 'chapter')},
        ),
        migrations.AlterUniqueTogether(
            name='highlighttag',
            unique_together={('highlight', 'tag')},
        ),
    ]
