# Generated by Django 6.0.3 on 2026-06-09 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, choices=[('teologia', 'Teología'), ('profecia', 'Profecía'), ('historia', 'Historia'), ('devocional', 'Devocional'), ('apologetica', 'Apologética'), ('biblia', 'Estudio Bíblico'), ('liderazgo', 'Liderazgo'), ('otro', 'Otro')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, upload_to='books/covers/%Y/%m/')),
                ('pdf_key', models.CharField(blank=True, max_length=500)),
                ('pdf_filename', models.CharField(blank=True, max_length=255)),
                ('total_pages', models.PositiveIntegerField(default=0)),
                ('current_page', models.PositiveIntegerField(default=0)),
                ('daily_goal', models.PositiveIntegerField(default=10)),
                ('is_finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BookSubtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('y_position', models.FloatField(default=0.5)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='bible.studybook')),
            ],
            options={
                'ordering': ['page_number', 'y_position'],
            },
        ),
        migrations.CreateModel(
            name='BookReadingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('page_start', models.PositiveIntegerField()),
                ('page_end', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_logs', to='bible.studybook')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StudyFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#93C5FD', max_length=7)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BookPageNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_page_notes', to='bible.highlightcategory')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_notes', to='bible.studybook')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_page_notes', to='bible.studyfolder')),
            ],
            options={
                'ordering': ['page_number', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('selected_text', models.TextField()),
                ('rect_data', models.JSONField(default=list)),
                ('annotation', models.TextField(blank=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('color', models.CharField(default='#FDE047', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_highlights', to='bible.highlightcategory')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='bible.studybook')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_highlights', to='bible.studyfolder')),
            ],
            options={
                'ordering': ['page_number', 'created_at'],
            },
        ),
    ]
