# Generated by Django 6.0.3 on 2026-03-23 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('author_name', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, choices=[('god', 'Dios'), ('bible', 'Biblia'), ('life', 'Vida'), ('prophecy', 'Profecía'), ('change', 'Cambio'), ('relationships', 'Relaciones'), ('youth', 'Jóvenes')], max_length=15)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True, max_length=500)),
                ('cover_image', models.ImageField(blank=True, upload_to='articles/covers/')),
                ('external_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ChurchService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('service_type', models.CharField(choices=[('webcast', 'Webcast'), ('sermon', 'Sermón'), ('bible_study', 'Estudio Bíblico'), ('special', 'Especial')], max_length=12)),
                ('description', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('audio_url', models.URLField(blank=True)),
                ('speaker', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField()),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('audio_url', models.URLField()),
                ('cover_image', models.ImageField(blank=True, upload_to='podcasts/covers/')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('episode_number', models.PositiveIntegerField(blank=True, null=True)),
                ('series', models.CharField(blank=True, max_length=100)),
                ('external_url', models.URLField(blank=True)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('podcast', 'Podcast'), ('article', 'Artículo'), ('service', 'Servicio')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.article')),
                ('podcast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.podcast')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.churchservice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
