# Generated by Django 6.0.3 on 2026-03-23 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada'), ('cancelled', 'Cancelada'), ('completed', 'Completada')], default='pending', max_length=10)),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('arrival_date', models.DateField(verbose_name='Fecha de llegada')),
                ('departure_date', models.DateField(verbose_name='Fecha de salida')),
                ('num_guests', models.PositiveSmallIntegerField(default=1, verbose_name='Número de huéspedes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosting_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosting_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HostingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='hosting.hostingrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='HostProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('max_guests', models.PositiveSmallIntegerField(default=1, verbose_name='Capacidad')),
                ('description', models.TextField(blank=True, verbose_name='Descripción del hospedaje')),
                ('address_city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('address_country', models.CharField(max_length=5, verbose_name='País')),
                ('amenities', models.TextField(blank=True, verbose_name='Comodidades')),
                ('rules', models.TextField(blank=True, verbose_name='Reglas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='host_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['address_country', 'address_city'],
            },
        ),
    ]
