# Generated by Django 6.0.3 on 2026-06-09 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Cuenta privada'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(default='es', max_length=10, verbose_name='Idioma preferido'),
        ),
        migrations.CreateModel(
            name='UserLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('language_name', models.CharField(max_length=50)),
                ('is_native', models.BooleanField(default=False)),
                ('proficiency', models.CharField(choices=[('native', 'Nativo'), ('fluent', 'Fluido'), ('intermediate', 'Intermedio'), ('beginner', 'Principiante')], default='intermediate', max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_native', 'language_name'],
                'unique_together': {('user', 'language_code')},
            },
        ),
    ]
