# Generated by Django 6.0.3 on 2026-04-17 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('text', 'Texto'), ('article', 'Artículo'), ('testimony', 'Testimonio'), ('news', 'Novedad'), ('devotional', 'Devocional'), ('hobby', 'Hobby')], default='text', max_length=15),
        ),
    ]
