# Generated by Django 6.0.3 on 2026-07-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_add_hobby_type_and_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', 'Todos'), ('friends', 'Amigos')], default='public', max_length=10),
        ),
    ]
